# Docker compose file for lvlie docker images. We use the automatically built docker images from the hub, so we dont specify the build key. 
# The source however is in the same git repository. 

version: '2' 

services:
  shellinabox:
    container_name: shellinabox
    hostname: shellinabox
    build: ./shellinabox
    image: docker.io/lvlie/shellinabox
    ports:
      - "4200:4200"
    volumes:
      - /etc/localtime:/etc/localtime:ro
    restart: always
  proxy:
    container_name: proxy
    hostname: proxy
    build: ./proxy
    image: docker.io/lvlie/proxy
    ports:
      - "443:443"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/config/httpd/:/config/httpd/:ro
      - /etc/letsencrypt/:/config/ssl/:ro
    restart: always
  sabnzbd:
    container_name: sabnzbd
    hostname: sabnzbd
    build: ./sabnzbd
    image: docker.io/lvlie/sabnzbd
    ports:
      - "8088:8080"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/config/sabnzbd:/config/sabnzbd/
      - /srv/cache/:/cache/
      - /srv/:/data/
    restart: always
  plex:
    container_name: plex
    hostname: plex
    build: ./plex
    image: docker.io/lvlie/plex
    network_mode: "host"
    volumes: 
      - /etc/localtime:/etc/localtime:ro
      - /var/config/plex/:/config/plex/
      - /srv/:/data/
    restart: always
  timemachine:
    container_name: timemachine
    hostname: timemachine
    build: ./timemachine
    image: docker.io/lvlie/timemachine
    network_mode: "host"
    volumes: 
      - /etc/localtime:/etc/localtime:ro
      - /srv/backup/:/backup/
    restart: always
  plexpy:
    container_name: plexpy
    hostname: plexpy
    build: ./plexpy
    image: docker.io/lvlie/plexpy
    ports:
      - "8181:8181/tcp"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/config/plexpy/:/config/plexpy
    restart: always
  sonarr:
    container_name: sonarr
    hostname: sonarr
    build: ./sonarr
    image: docker.io/lvlie/sonarr
    ports:
      - "8989:8989/tcp"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/config/sonarr/:/config/sonarr
      - /srv/TV/:/data/TV/
      - /srv/cache/:/cache/
    restart: always
  radarr:
    container_name: radarr
    hostname: radarr
    build: ./radarr
    image: docker.io/lvlie/radarr
    ports:
      - "7878:7878/tcp"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/config/radarr/:/config/radarr
      - /srv/Movies/:/data/Movies/
      - /srv/cache/:/cache/
    restart: always
  unifi:
    container_name: unifi
    hostname: unifi
    image: docker.io/linuxserver/unifi:latest
    ports:
      - "8080:8080"
      - "8081:8081"
      - "8443:8443"
      - "8843:8843"
      - "8880:8880"
      - "3478:3478/udp"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/config/unifi/:/config
    restart: always
    environment:
      - PUID=800
      - PGID=1000
  hass:
    container_name: hass
    hostname: hass
    image: docker.io/homeassistant/home-assistant
    network_mode: "host"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/config/hass/:/config/
    restart: always
  duplicity:
    container_name: duplicity
    hostname: duplicity
    build: ./duplicity
    image: docker.io/lvlie/duplicity
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/config/:/config/:ro
      - /srv/unifi/:/data/unifi/:ro
      - /home/:/home/:ro
      - /var/backup/:/backup/
      - /var/log/duplicity/:/var/log/duplicity/
      - /etc/duplicity/:/etc/duplicity/:ro
    restart: always
