version: '2' 

services:
  nginx:
    container_name: nginx
    hostname: nginx
    image: docker.io/linuxserver/letsencrypt:latest
    cap_add:
      - NET_ADMIN
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/config/nginx/:/config/
    restart: always
    environment:
      - TZ=Europe/Amsterdam
      - PUID=800
      - PGID=1000
      - EMAIL=${EMAIL} 
      - URL=${DOMAIN}
      - SUBDOMAINS=${SUBDOMAINS}
      - VALIDATION=${VALIDATION}
      - DHLEVEL=4096
  shellinabox:
    container_name: shellinabox
    hostname: shellinabox
    build: ./shellinabox
    image: docker.io/lvlie/shellinabox
    ports:
      - "4200:4200"
    volumes:
      - /etc/localtime:/etc/localtime:ro
    restart: always
  sabnzbd:
    container_name: sabnzbd
    hostname: sabnzbd
    image: docker.io/linuxserver/sabnzbd:latest
    ports:
      - "8088:8080"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/config/sabnzbd/:/config/
      - /srv/cache/incomplete:/incomplete-downloads/
      - /srv/cache/complete:/downloads/
      - /srv/:/data
    restart: always
    environment:
      - TZ=Europe/Amsterdam
      - PUID=800
      - PGID=1000
  plex:
    container_name: plex
    hostname: plex
    image: docker.io/plexinc/pms-docker:latest
    ports:
      - 32400:32400/tcp
      - 3005:3005/tcp
      - 8324:8324/tcp
      - 32469:32469/tcp
      - 1900:1900/udp
      - 32410:32410/udp
      - 32412:32412/udp
      - 32413:32413/udp
      - 32414:32414/udp
    volumes: 
      - /etc/localtime:/etc/localtime:ro
      - /var/config/plex/:/config/
      - /var/config/plex/temp/Transcode/:/transcode/
      - /srv/:/data/
    restart: always
    environment:
      - TZ=Europe/Amsterdam
      - PLEX_UID=800
      - PLEX_GID=1000
      - ADVERTISE_IP="${ADVERTISE_IP}"
  timemachine:
    container_name: timemachine
    hostname: timemachine
    build: ./timemachine
    image: docker.io/lvlie/timemachine
    network_mode: "host"
    volumes: 
      - /etc/localtime:/etc/localtime:ro
      - /srv/backup/:/backup/
    restart: always
  tautulli:
    container_name: tautulli
    hostname: tautulli
    image: docker.io/linuxserver/tautulli:latest
    ports:
      - "8181:8181/tcp"
    volumes:
      - /var/config/plexpy/:/config
      - /var/config/plex/Library/Logs/:/logs:ro
    restart: always
    environment:
      - TZ=Europe/Amsterdam
      - PUID=800
      - PGID=1000
  sonarr:
    container_name: sonarr
    hostname: sonarr
    image: docker.io/linuxserver/sonarr:latest
    ports:
      - "8989:8989/tcp"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/config/sonarr/:/config/
      - /srv/TV/:/tv/
      - /srv/cache/complete:/downloads/
    restart: always
    environment:
      - TZ=Europe/Amsterdam
      - PUID=800
      - PGID=1000
  radarr:
    container_name: radarr
    hostname: radarr
    image: docker.io/linuxserver/radarr:latest
    ports:
      - "7878:7878/tcp"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/config/radarr/:/config/
      - /srv/Movies/:/movies/
      - /srv/cache/complete:/downloads/
    restart: always
    environment:
      - TZ=Europe/Amsterdam
      - PUID=800
      - PGID=1000
  unifi:
    container_name: unifi
    hostname: unifi
    image: docker.io/linuxserver/unifi:latest
    ports:
      - "8080:8080"
      - "8081:8081"
      - "8443:8443"
      - "8843:8843"
      - "8880:8880"
      - "3478:3478/udp"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/config/unifi/:/config
    restart: always
    environment:
      - TZ=Europe/Amsterdam
      - PUID=800
      - PGID=1000
  db:
    container_name: db
    hostname: db
    image: mariadb:latest
    ports:
      - "3306:3306"
    volumes:
      - /var/config/mariadb/:/var/lib/mysql
    restart: always
    environment:
      MYSQL_DATABASE: "homeassistant"
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
      MYSQL_USER: "${MYSQL_USER}"
      MYSQL_PASSWORD: "${MYSQL_PASSWORD}"
  hass:
    container_name: hass
    hostname: hass
    image: docker.io/homeassistant/home-assistant:latest
    network_mode: "host"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/config/hass/:/config/
    devices:
      - "/dev/ttyACM0:/dev/ttyACM0"
      - "/dev/ttyUSB0:/dev/ttyUSB0"
    restart: always
    depends_on:
      - db
      - influx
      - plex
      - sonarr
      - radarr
      - unifi
  duplicati:
    container_name: duplicati
    hostname: duplicati
    image: docker.io/linuxserver/duplicati:latest
    ports:
      - "8200:8200"
    volumes:
      - /var/config/:/backup/var/config/:ro
      - /srv/backup/:/backup/srv/backup/:ro
      - /home/:/backup/home/:ro
      - /var/config/duplicati/:/config
    restart: always
    environment:
      - TZ=Europe/Amsterdam
      - PUID=800
      - PGID=1000
  influx:
    container_name: influx
    hostname: influx
    image: influxdb:latest
    ports:
      - "8083:8083"
      - "8086:8086"
      - "8090:8090"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/srv/db/influx/:/var/lib/influxdb
    restart: always
  grafana:
    container_name: grafana
    hostname: grafana
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/srv/db/grafana/:/var/lib/grafana
    restart: always
    depends_on:
      - influx
    environment:
      GF_DEFAULT_INSTANCE_NAME: "home"
      GF_AUTH_BASIC_ENABLED: "false"
      GF_AUTH_ANONYMOUS_ENABLED: "true"
      GF_AUTH_ANONYMOUS_ORG_NAME: "home"
      GF_AUTH_ANONYMOUS_ORG_ROLE: "Admin"
      GF_SERVER_PROTOCOL: http
      GF_SERVER_DOMAIN: "${DOMAIN}"
      GF_SERVER_ROOT_URL: "%(protocol)s://%(domain)s:/grafana"
  telegraf:
    container_name: telegraf
    hostname: telegraf
    image: telegraf:latest
    network_mode: "host"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/config/telegraf/telegraf.conf:/etc/telegraf/telegraf.conf:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
    restart: always
    depends_on:
      - influx
  watchtower:
    container_name: watchtower
    hostname: watchtower
    image: v2tec/watchtower:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --schedule "0 2 * * * *"
    restart: always
  nodered:
    container_name: nodered
    hostname: nodered
    image: nodered/node-red-docker:v8
    ports:
      - "1880:1880"
    volumes:
      - /var/config/node-red/:/data
    restart: always
    environment:
      - TZ=Europe/Amsterdam
